import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const TEAL: [number, number, number] = [20, 184, 166];
const DARK: [number, number, number] = [15, 23, 42];
const MUTED: [number, number, number] = [100, 116, 139];

function safeName(s: string): string {
  return String(s || "document").replace(/\s+/g, "_").replace(/[^A-Za-z0-9_\-]/g, "");
}

function header(doc: jsPDF, title: string) {
  doc.setFillColor(...DARK);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 18, "F");
  doc.setTextColor(...TEAL);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("ContractIQ SA", 14, 12);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(title, doc.internal.pageSize.getWidth() - 14, 12, { align: "right" });
  doc.setTextColor(0, 0, 0);
}

function footer(doc: jsPDF, ref: string) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const w = doc.internal.pageSize.getWidth();
    const h = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(`ContractIQ SA · ${ref}`, 14, h - 8);
    doc.text(`Page ${i} of ${pageCount}`, w - 14, h - 8, { align: "right" });
  }
}

function section(doc: jsPDF, title: string, y: number): number {
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...TEAL);
  doc.text(title, 14, y);
  doc.setDrawColor(...TEAL);
  doc.line(14, y + 1.5, doc.internal.pageSize.getWidth() - 14, y + 1.5);
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "normal");
  return y + 8;
}

function ensureSpace(doc: jsPDF, y: number, needed = 30): number {
  if (y + needed > doc.internal.pageSize.getHeight() - 15) {
    doc.addPage();
    return 25;
  }
  return y;
}

export function downloadFullReport(master: any, doc_meta: { file_name: string; reference?: string }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const tri = master?.triage ?? {};
  const sub = master?.submission?.submission ?? {};
  const ref = tri?.reference_number || doc_meta.reference || doc_meta.file_name;

  // Cover
  header(doc, "Full Procurement Intelligence Report");
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...TEAL);
  doc.text("Procurement Intelligence Report", 14, 50);
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text(String(tri?.tender_title ?? doc_meta.file_name), 14, 60, { maxWidth: 180 });
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  doc.text(`Reference: ${tri?.reference_number ?? "—"}`, 14, 80);
  doc.text(`Issuing authority: ${tri?.issuing_entity ?? "—"}`, 14, 86);
  doc.text(`Closing: ${sub?.closing_date ?? "—"} ${sub?.closing_time ?? ""}`, 14, 92);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 98);
  if (master?.meta?.overall_confidence != null) {
    doc.text(`Overall confidence: ${Math.round(master.meta.overall_confidence * 100)}%`, 14, 104);
  }
  doc.setFontSize(9);
  doc.text(
    "This report was generated by ContractIQ SA AI extraction. Users must verify all\ninformation against the original tender document before use in any submission.",
    14, 270
  );

  // Executive summary
  doc.addPage();
  header(doc, "Executive Summary");
  let y = 30;
  y = section(doc, "Executive Summary", y);
  doc.setFontSize(11);
  doc.text(String(master?.procurement_summary?.one_line ?? "—"), 14, y, { maxWidth: 180 });
  y += 16;
  const viab: string[] = master?.procurement_summary?.bid_viability_factors ?? [];
  if (viab.length) {
    y = section(doc, "Bid Viability Factors", y);
    doc.setFontSize(10);
    for (const v of viab) {
      y = ensureSpace(doc, y, 8);
      doc.text(`• ${v}`, 14, y, { maxWidth: 180 });
      y += 6;
    }
  }

  // Risk flags
  const flags: any[] = master?.risk_flags ?? [];
  if (flags.length) {
    doc.addPage();
    header(doc, "Risk Flags");
    autoTable(doc, {
      startY: 30,
      head: [["Severity", "Category", "Flag", "Action Required", "Page"]],
      body: flags.map((f) => [f.severity, f.category, f.flag, f.action_required, f.page_reference]),
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: TEAL },
      didParseCell: (data) => {
        if (data.section === "body" && data.column.index === 0) {
          const s = String(data.cell.raw).toLowerCase();
          if (s === "critical") data.cell.styles.fillColor = [239, 68, 68];
          else if (s === "high") data.cell.styles.fillColor = [249, 115, 22];
          else if (s === "medium") data.cell.styles.fillColor = [234, 179, 8];
          data.cell.styles.textColor = [255, 255, 255];
        }
      },
    });
  }

  // Submission
  doc.addPage();
  header(doc, "Submission Requirements");
  const subRows = [
    ["Closing date", sub?.closing_date], ["Closing time", sub?.closing_time],
    ["Method", sub?.submission_method], ["Address", sub?.physical_address],
    ["Number of copies", sub?.number_of_copies], ["Portal", sub?.portal_name],
    ["Briefing", master?.submission?.submission?.briefing_session?.mandatory ? "Mandatory" : "Optional"],
  ].filter(([, v]) => v != null && v !== "");
  autoTable(doc, { startY: 30, head: [["Field", "Value"]], body: subRows as any, styles: { fontSize: 9 }, headStyles: { fillColor: TEAL } });

  // Compliance checklist
  const compl: any[] = master?.compliance_checklist ?? master?.submission?.mandatory_compliance_documents ?? [];
  if (compl.length) {
    doc.addPage();
    header(doc, "Compliance Checklist");
    autoTable(doc, {
      startY: 30,
      head: [["Document", "Mandatory", "Disqualifies", "Page", "Notes"]],
      body: compl.map((d) => [d.document_name ?? d.name, d.mandatory ? "Yes" : "No", d.disqualifies_if_missing ? "Yes" : "No", d.page_reference ?? d.page ?? "", d.notes ?? ""]),
      styles: { fontSize: 8 }, headStyles: { fillColor: TEAL },
    });
  }

  // Returnables
  const rets: any[] = master?.returnables?.returnables ?? [];
  if (rets.length) {
    doc.addPage();
    header(doc, "Returnables Checklist");
    autoTable(doc, {
      startY: 30,
      head: [["Name", "Page", "Type", "Mandatory", "Sig", "Comm", "Stamp", "Witness"]],
      body: rets.map((r) => [
        r.name, r.page_number, r.form_type, r.mandatory ? "Y" : "N",
        r.requires_signature ? "Y" : "N", r.requires_commissioner_of_oaths ? "Y" : "N",
        r.requires_company_stamp ? "Y" : "N", r.requires_witness ? "Y" : "N",
      ]),
      styles: { fontSize: 8 }, headStyles: { fillColor: TEAL },
    });
  }

  // Evaluation
  const ev = master?.evaluation?.evaluation_methodology;
  if (ev) {
    doc.addPage();
    header(doc, "Evaluation Criteria");
    let yy = 30;
    yy = section(doc, "Evaluation Methodology", yy);
    doc.setFontSize(9);
    doc.text(String(ev.overall_description ?? "—"), 14, yy, { maxWidth: 180 });
    const fc: any[] = ev.stage_2_functionality?.criteria ?? [];
    if (fc.length) {
      autoTable(doc, {
        startY: yy + 14,
        head: [["Criterion", "Weight", "Max", "Scoring Guide", "Page"]],
        body: fc.map((c) => [c.criterion, c.weight, c.maximum_points, c.scoring_guide, c.page_reference]),
        styles: { fontSize: 8 }, headStyles: { fillColor: TEAL },
      });
    }
  }

  // Pricing
  const schedules: any[] = master?.pricing?.pricing_schedules ?? [];
  if (schedules.length) {
    doc.addPage();
    header(doc, "Pricing Schedules");
    let yy = 30;
    for (const sch of schedules) {
      yy = section(doc, `${sch.schedule_name ?? "Schedule"} (Page ${sch.page_number ?? "?"})`, yy);
      autoTable(doc, {
        startY: yy,
        head: [["Item", "Description", "Unit", "Qty", "Rate", "Amount"]],
        body: (sch.rows ?? []).map((r: any) => [r.item_no, r.description, r.unit, r.quantity, r.rate_column, r.amount_column]),
        styles: { fontSize: 7 }, headStyles: { fillColor: TEAL },
      });
      yy = (doc as any).lastAutoTable.finalY + 8;
      yy = ensureSpace(doc, yy, 50);
    }
  }

  // Contract terms
  const con = master?.contract;
  if (con) {
    doc.addPage();
    header(doc, "Contract Terms");
    let yy = 30;
    const rows = [
      ["Duration", con.contract_duration], ["Penalties", con.penalties_and_damages],
      ["Payment terms", con.payment_terms?.payment_period_days ? `${con.payment_terms.payment_period_days} days` : null],
      ["Force majeure", con.force_majeure], ["Cession", con.cession_and_assignment],
      ["Price adjustment", con.price_adjustment_mechanism], ["Community participation", con.community_participation],
    ].filter(([, v]) => v != null && v !== "");
    autoTable(doc, { startY: yy, head: [["Clause", "Detail"]], body: rows as any, styles: { fontSize: 8 }, headStyles: { fillColor: TEAL } });
  }

  // Page intel
  const pi: any[] = master?.page_level_intelligence ?? [];
  if (pi.length) {
    doc.addPage();
    header(doc, "Page Intelligence");
    autoTable(doc, {
      startY: 30,
      head: [["Page", "Section", "Action", "Mandatory", "Confidence"]],
      body: pi.map((p) => [p.page, p.section_type, p.action, p.mandatory ? "Y" : "N", p.confidence]),
      styles: { fontSize: 8 }, headStyles: { fillColor: TEAL },
    });
  }

  // Missing data
  const md: any[] = master?.missing_data ?? [];
  if (md.length) {
    doc.addPage();
    header(doc, "Missing Data");
    autoTable(doc, {
      startY: 30,
      head: [["Field", "Reason"]],
      body: md.map((m: any) => [m.field ?? "", m.reason ?? ""]),
      styles: { fontSize: 9 }, headStyles: { fillColor: TEAL },
    });
  }

  footer(doc, String(ref));
  doc.save(`ContractIQ_${safeName(String(ref))}_FullReport_${new Date().toISOString().slice(0, 10)}.pdf`);
}

export function downloadReturnablesPDF(master: any, doc_meta: { file_name: string }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const tri = master?.triage ?? {};
  const ref = tri?.reference_number || doc_meta.file_name;
  header(doc, "Returnables Checklist");
  let y = 30;
  for (const r of master?.returnables?.returnables ?? []) {
    y = ensureSpace(doc, y, 50);
    y = section(doc, `${r.name ?? "Returnable"} — Page ${r.page_number ?? "?"}`, y);
    doc.setFontSize(9);
    const badges: string[] = [];
    if (r.mandatory) badges.push("MANDATORY");
    if (r.disqualifies_if_missing) badges.push("DISQUALIFIES");
    if (r.requires_signature) badges.push("SIGNATURE");
    if (r.requires_commissioner_of_oaths) badges.push("COMMISSIONER");
    if (r.requires_company_stamp) badges.push("STAMP");
    if (r.requires_witness) badges.push("WITNESS");
    doc.setTextColor(...MUTED);
    doc.text(badges.join(" · "), 14, y); y += 6;
    doc.setTextColor(0, 0, 0);
    const fields: string[] = r.fields_to_complete ?? [];
    for (let i = 0; i < fields.length; i++) {
      y = ensureSpace(doc, y, 14);
      doc.text(`${i + 1}. ${fields[i]}`, 14, y); y += 5;
      doc.setDrawColor(180); doc.line(14, y + 2, 196, y + 2); y += 10;
    }
    y = ensureSpace(doc, y, 20);
    doc.setFontSize(8); doc.setTextColor(...MUTED);
    doc.text(`Purpose: ${r.purpose ?? ""}`, 14, y, { maxWidth: 180 }); y += 6;
    doc.text("Signed: ____________________   Date: ____________   ☐ Complete", 14, y); y += 12;
    doc.setTextColor(0, 0, 0);
  }
  footer(doc, String(ref));
  doc.save(`ContractIQ_${safeName(String(ref))}_Returnables_${new Date().toISOString().slice(0, 10)}.pdf`);
}

export function downloadSubmissionPackPDF(items: any[], master: any, doc_meta: { file_name: string }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const tri = master?.triage ?? {};
  const sub = master?.submission?.submission ?? {};
  const ref = tri?.reference_number || doc_meta.file_name;
  header(doc, "Submission Pack Order");
  doc.setFontSize(11); doc.setFont("helvetica", "bold");
  doc.text(`Closing: ${sub?.closing_date ?? "—"} ${sub?.closing_time ?? ""}`, 14, 28);
  autoTable(doc, {
    startY: 36,
    head: [["#", "✓", "Document", "Page", "Mandatory", "Disqualifies"]],
    body: items.map((it, i) => [
      i + 1, "☐", it.name, it.page_number ?? "",
      it.mandatory ? "YES" : "no", it.disqualifies_if_missing ? "YES" : "no",
    ]),
    styles: { fontSize: 9 }, headStyles: { fillColor: TEAL },
  });
  const yy = (doc as any).lastAutoTable.finalY + 14;
  doc.setFontSize(9); doc.setFont("helvetica", "normal");
  doc.text(
    "I confirm that all documents listed above are correctly completed, properly signed,\ncommissioned where required, and ready for submission in the correct order.",
    14, yy
  );
  doc.text("Signature: ____________________   Name: ____________________   Date: ____________", 14, yy + 18);
  footer(doc, String(ref));
  doc.save(`ContractIQ_${safeName(String(ref))}_SubmissionPack_${new Date().toISOString().slice(0, 10)}.pdf`);
}

export function downloadJSON(master: any, doc_meta: { file_name: string; reference?: string }) {
  const ref = master?.triage?.reference_number || doc_meta.reference || doc_meta.file_name;
  const blob = new Blob([JSON.stringify(master, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = `ContractIQ_${safeName(String(ref))}_Raw_${new Date().toISOString().slice(0, 10)}.json`;
  document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url);
}
